# Generated by Django 4.0.6 on 2022-07-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_database.event'),
        ),
    ]
