# Generated by Django 4.0.6 on 2022-07-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_database', '0002_alter_attendee_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='events',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_database.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_database.attendee'),
        ),
    ]
