# Generated by Django 4.0.6 on 2022-07-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_database', '0003_alter_attendee_events_alter_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.CreateModel(
            name='Attendee_Event_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_database.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_database.event')),
            ],
        ),
    ]
