# Generated by Django 4.0.6 on 2022-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_database', '0004_remove_attendee_events_remove_event_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timer',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
