# Generated by Django 4.0.6 on 2022-07-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_database', '0005_alter_slot_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_database.attendee'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_database.organizer'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='boundary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
